[package]
name = "alpacka"
version = "0.1.0"
authors = ["Your Name <your@email.com>"]

[dependencies]
clap = "4.1"
dirs = "4.0"
git2 = "0.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
