[package]
name = "alpacka"
version = "0.1.0"
description = "Cli-based package manager for neovim"
repository = "https://github.com/nyoom-engineering/alpacka"
authors = ["Shaurya Singh <shaunsingh0207@gmail.com>", "Suyashtnt"]
license = "MIT"
categories = ["command-line-utilities", "text-editors"]
keywords = ["vim", "neovim", "package", "plugin", "manager"]
edition = "2021"

[dependencies]
bincode2 = "2.0"
bytecheck = "0.6.9"
error-stack = "0.2.4"
git2 = "0.16.1"
hashbrown = { version = "0.13.2", features = ["serde"] }
rkyv = { version = "0.7.39", features = ["validation"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
termcolor = "1.2"
tracing = "0.1"
tracing-subscriber = "0.3"
