[package]
authors = ["Shaurya Singh <shaunsingh0207@gmail.com>", "Suyashtnt"]
categories = ["command-line-utilities", "text-editors"]
description = "Cli-based package manager for neovim"
edition = "2021"
keywords = ["vim", "neovim", "package", "plugin", "manager"]
license = "MIT"
name = "alpacka"
version = "0.1.0"
repository = "https://github.com/nyoom-engineering/alpacka"

[dependencies]
clap = "4.1"
git2 = "0.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

