[package]
name = "alpacka"
version = "0.1.0"
description = "Cli-based package manager for neovim"
repository = "https://github.com/nyoom-engineering/alpacka"
authors = ["Shaurya Singh <shaunsingh0207@gmail.com>", "Suyashtnt"]
license = "MIT"
categories = ["command-line-utilities", "text-editors"]
keywords = ["vim", "neovim", "package", "plugin", "manager"]
edition = "2021"

[dependencies]
anyhow = "1.0"
bincode2 = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
termcolor = "1.2"

