# built against standard cargo
name: "cargo build and publish"
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'main'
      - 'ci*' # Allow testing CI fixes without opening a PR

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: build alpacka
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: upload alpacka binary
        uses: actions/upload-artifact@v2
        with:
          name: "alpacka-linux-x86_64"
          path: "target/release/alpacka"
          if-no-files-found: error
          retention-days: 7

  macos:
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: brew install openssl
      - uses: actions/checkout@v2
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: build apacka
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: upload alpacka x86 mac binary
        uses: actions/upload-artifact@v2
        with:
          name: "alpacka-macos-x86_64"
          path: "target/release/alpacka"
          if-no-files-found: error
          retention-days: 7

  macos-m1:
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: brew install openssl git
      - uses: actions/checkout@v2
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v1
      - uses: goto-bus-stop/setup-zig@v2
      - name: install zigbuild
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-zigbuild
      - uses: maxim-lobanov/setup-xcode@v1 # required for compiling openssl-sys it seems
        with:
          xcode-version: latest-stable
      - name: build alpacka
        uses: actions-rs/cargo@v1
        with:
          command: zigbuild
          args: --release --features vendor --target aarch64-apple-darwin
      - name: upload alpacka aarch64 binary
        uses: actions/upload-artifact@v2
        with:
          name: "alpacka-macos-aarch64"
          path: "target/aarch64-apple-darwin/release/alpacka"
          if-no-files-found: error
          retention-days: 7
