name: "nix test suite"
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'main'
      - 'ci*' # Allow testing CI fixes without opening a PR

permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        include:
            # Latest and greatest release of Nix
          - name: nixpkgs (latest)
            install_url: https://nixos.org/nix/install
            # The 22.11 branch ships with Nix 2.11.1
          - name: nixpkgs (22.11)
            install_url: https://releases.nixos.org/nix/nix-2.11.1/install
            nixpkgs-override: "--override-input nixpkgs github:NixOS/nixpkgs/release-22.11"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v21
      with:
        install_url: ${{ matrix.install_url }}
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v12
      with:
        name: nyoom-engineering
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: flake checks
      run: nix flake check --keep-going --print-build-logs ${{ matrix.nixpkgs-override }} --no-sandbox
